worker_processes auto;

events {
    worker_connections 1024;
}

http {

    upstream songInfoCluster {
        server song-info;
    }

    server {
        listen 80;
        server_name song-info;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name song-info;

        ssl_certificate     /etc/nginx/ssl/fullchain.crt;
        ssl_certificate_key /etc/nginx/ssl/privkey.key;

        location / {

            proxy_pass http://song-info:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}