spring:
  application:
    name: songInfo
  datasource:
    url: jdbc:postgresql://songInfoPostgres:5432/${SONG_INFO_DB_NAME}
    username: ${SONG_INFO_DB_USER}
    password: ${SONG_INFO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory:
              type: local-filesystem
              root: ${SOND_DB_INDEX_STORAGE}
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      encoding: UTF-8

webclient:
  token: ${AIRTABLE_ENV}
admin:
  password: ${ADMIN_PASSWORD}
  username: ${ADMIN_USERNAME}
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"  # Ensure that the Prometheus endpoint is exposed
  metrics:
    export:
      prometheus:
        enabled: true  # Enable Prometheus export
